version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8
      - image: cimg/postgres:14.0.0
        environment:
           POSTGRES_USER: test-user
           POSTGRES_DB: test-db
           POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            echo "hello james njiruuuuuuuu"
            echo $POSTGRES_USER
workflows:
  sample: 
    jobs:
      - build-and-test
