version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.10 
      - image: circleci/postgres:10.6-alpine-ram
        environment:
          DB_USER: test-user
          DB_NAME: test-db
          DB_PASSWORD: ""
    working_directory: ~/repo

    steps:
      # checkout is used to check out source code
      - checkout
  
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - &InstallDependencies
        run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      # use catch to save time between runs
      # save to cache certain files
      - save_cache:
            paths:
              - ./venv
            key: v2-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: run tests
          no_output_timeout: 30m
          command: |
            . venv/bin/activate
            pytest
workflows:
  version: 2
  build:
    jobs:
      - build
